main:
  name: NuPyBuilder
  version: 0.0.4.2
  author: intervision
  authorlink: https://github.com/intervisionlord

default_params:
  - windows-disable-console
  - follow-imports
  - onefile
  - standalone
  - remove-output
  - windows-product-name="NuPyProject"
  - windows-company-name="CompanyName"
  - windows-product-version="0.0.0.0"
  - windows-file-description="Product description"