main:
  name: NuPyBuilder
  version: 0.0.1.6b
  author: intervision
  authorlink: https://github.com/intervisionlord

default_params:
  - windows-disable-console
  - follow-imports
  - onefile
  - standalone
  - remove-output
  - windows-product-name="NuPyProject"
  - windows-company-name="CompanyName"
  - windows-product-version
  - windows-file-description="Product description"

# main:
#   product_name: Product
#   version: '0.0.1.0'
#   author: 'intervision'
#   authorlink: 'https://github.com/intervisionlord'
#   icon: '../ui/imgs/flask.png'

# source:
#   mainfile: mainfile
#   outputfile: outfile
#   workdir: workdir

# plugins: pyqt5

# # files:
# #   - ui/imgs/open.png
# #   - ui/imgs/reset.png
# #   - ui/imgs/flask.png