main:
  product_name: Your Product's name
  version: '0.0.1.0' # 4 digits prefered
  author: Your Name
  authorlink: URL tp Your website
  icon: Path to Icon of your app # abs. pathg prefered

source:
  mainfile: path to the main file of your application (*.py)
  outputfile: path to the output file of your application (*.exe)
  workdir: workdir where your application will be compiled

  plugins: #pyqt5 for example

params:
  - windows-disable-console
  - follow-imports
  - onefile
  - standalone
  - remove-output
  - windows-product-name="Product Name"
  - windows-company-name="Company Name"
  - windows-product-version
  - windows-file-description="Product description"

files:
  # - List of files to add to the archive with main file
  # - ui/imgs/open.png
  # - ui/imgs/reset.png
  # - ui/imgs/flask.png