main:
  product_name: # Product name e.g.: "My Program"
  version: # Version (4 digits dot separated, like 1.0.0.0)
  author: # Author or developer name
  authorlink: # Author's website
  icon: # Path to your program icon with straight slashes (e.g.: "some/path/app.ico")
  archive: # Pack your app in ZIP archive with all addition files ("yes / no")

source:
  mainfile: # Path to *.py main file with straight slashes (e.g.: "some/path/app.py")
  outputfile: # Final file name (like app.exe)
  workdir: # Deprecated

plugins: # Requiered plugins like pyqt5 or other

params: # All requiered parameters for Nuitka
  - windows-disable-console
  - follow-imports
  - onefile
  - standalone
  - remove-output
  - windows-product-name="My App"
  - windows-company-name="My Company"
  - windows-product-version="0.0.0.0"
  - windows-file-description="My App Description"
  - output-dir="" # Path with straight slashes where your compiled app would be placed

files: # All additional files that should be placed with your app
  - # path/to/some/file.ext
  - # path/to/another/file.ext